# Generated by Django 4.2.7 on 2023-12-03 09:40

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='note',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
